### PR TITLE
Migrate deprecated AGP dsl

### PR DESCRIPTION
**Pull request by Goooler**
Something like `compileSdkVersion` is deprecated, we should migrate these API usages in both project and docs.

### CODE REVIEW

**Comment by poovamraj** [comment]
@Goooler this PR doesn't seem to change gradle-wrapper.properties and other required things like adding `namespace`. Are you sure this is building locally?

**Comment by Goooler** [comment]
Added `namespace`, I didn't update the wrapper files.

**Comment by Goooler** [comment]
The wrapper validation job need to be approved, see https://github.com/auth0/Auth0.Android/actions/runs/5745829757

**Comment by poovamraj** [comment]
Hey @Goooler looks like the build is failing and since we have are planning to do this migration ourselves in an upcoming initiative. We would like to close this PR. Thanks for the contribution though.

**Pull request closed without merging**
