### PR TITLE
Update to okhttp3 3.10.0

### PR DESCRIPTION
**Pull request by donatienthorez**
Notes : 
- There is still a test that failed that has been commented out line 212 in the BaseRequestTest.java. I cannot find out how to throw an IOException since calling twice response.body().string() does not throw an IOException anymore but just returns an empty string. 

Do you have an idea how to do it ?

- I had to put the test to run on sdk 23 or 25 because : 

 it got stucked when running the tests. The MockServer takeRequest method does not work well. 
https://github.com/square/okhttp/issues/3664

or

I have an AssertionError with clean text. More info here : https://github.com/square/okhttp/issues/2591

What do you think about the rest of the pull request ?

### CODE REVIEW

**Comment by friederbluemle** [comment]
It would be great to get this merged soon. Right now, the Auth0 SDK adds almost 5000 methods to the dex method count - it could be a lot less if the underlying networking lib matches what most apps are using (of course it would be best to have a little third-party dependencies in a library as possible, but that's beyond the scope of this PR).
Thanks.

**Comment by cocojoe** [comment]
Thanks, great contribution @donatienthorez, I'll have this reviewed. @lbalmaceda

**Comment by lbalmaceda** [comment]
This was already discussed before and there's an existing PR already #83. The problem is that things like [this](https://github.com/auth0/Auth0.Android/pull/151/files#diff-8645ce5636d53d051d1bc6d651d5a637R150) are breaking changes, since users will need to update their callbacks signature to match the new class that OkHttp uses. I plan to support it if a new major version of this library is to be made. But unfortunately, not today.

**Comment by TWiStErRob** [comment]
@lbalmaceda the [`auth0Domain` in Manifest](https://github.com/auth0/Auth0.Android/commit/284d9c80d8e6266efc00a06e9497b6876dd5d865#diff-ddec178edb3411a34da2d7f164d81ae7) was also a breaking change, this change would have a big benefit for app sizes. This is the last library we have that uses OkHttp 2 (2 years old version!).

**Comment by TWiStErRob** [comment]
Bump, 1.5 years passed, OkHttp 4 is alive and well.

**Comment by lbalmaceda** [comment]
@TWiStErRob I know, apologies for that. We will use the latest OKHttp version on the next Auth0.Android major. But while this major is around, that will not happen.

**Pull request closed without merging**
