### PR TITLE
Configure project for signing on Circle

### PR DESCRIPTION
**Pull request by frederikprijck**
### Changes

This PR sets the `skipAssertSigningConfiguration` flag to true, ensuring the OSS Gradle Plugin does not throw an error regarding missing properties, as we do not use these properties when signing on Circle CI.

It also updates the Circle CI config to ensure the signing project properties are correctly set based on environment variables.

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All existing and new tests complete without errors

### CODE REVIEW

**Comment by frederikprijck** [comment]
Needs https://github.com/auth0/oss-library-gradle-plugin/pull/35 to be merged and released first.

**Comment by frederikprijck** [comment]
https://github.com/auth0/oss-library-gradle-plugin/pull/35 has been merged, released and incorporated in this PR.

**Review by poovamraj — DISMISSED** [review]
+1 LGTM

**Comment by frederikprijck** [comment]
Marking as draft while we wait on a new release for the Circle Orb. Will bump the version in this PR once done.

**Review by poovamraj — APPROVED** [review]

**Pull request merged**
